server:
  mode: debug
  port: ':8080'
  version: v0.1
  static_dir: ./public
  max_multipart_memory: 10

database:
  url: 'postgres://root:root@localhost:5432/gin_postgres'
  max_idle_conns: 2
  max_open_conns: 16
