import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gin + React",
  description: "Generated by savvy-bit",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} text-[14px] antialiased font-[family-name:var(--font-geist-sans)]`}
      >
        <div className="w-screen min-h-screen flex flex-col">
          <header className="border-b border-dashed border-b-zinc-800 py-2 px-8">
            <Link href="/" >
              <Image src="/logo.png" alt="logo" width={71} height={48} className="h-12 w-auto object-contain" />
            </Link>
          </header>
          <div className="flex-1 flex flex-col max-w-[1440px] w-full m-auto p-8">
            {children}
          </div>
          <footer className="border-t border-dashed border-t-zinc-800 py-4">
            <p className="text-sm text-center">Copyright</p>
          </footer>
        </div>
        <ToastContainer
          theme="dark"
        />
      </body>
    </html>
  );
}
